# Generated by Django 2.2.6 on 2019-10-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team22ADV', '0002_auto_20191021_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
